print('************************************')
print('* frederico volkmann              *')
print('* rua ana braga                   *   ')
print('* badenfurt blumenau              *')
print('* santa catarina brasil           * ')
print('* cep 89087                       *')
print('************************************')